### ISSUE TITLE
Poloniex has disabled deposits and withdrawals for Gridcoin

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Erkan-Yilmaz/GRC#47]
Since [yesterday](https://poloniex.com/exchange#btc_grc) on Poloniex:
* "_GRC is currently under maintenance or experiencing wallet/network issues. Deposits and withdrawals will remain disabled until a solution is found, which may require an update from the GRC team. Any updates must be tested and audited before enabling._"

<br>

If I'd have to make a guess, it's because of the forkings. Likely, they also got on a fork :-(
* [Sep. 23](https://twitter.com/GridcoinIRC/status/911820732191137792)
* [Sep. 26](https://twitter.com/iFoggz/status/912501655681167360)

Best is to contact their support for further info...

<br>

Currently, Poloniex has 24.91% of the trading volume + BITTREX 74.37%

<br>

![polo_grc](https://user-images.githubusercontent.com/642286/30843156-a5e0837e-a287-11e7-9f79-7a29a400b95d.png)

**Comment by Erkan-Yilmaz** [comment]
These forkings are not a new problem:
* see since July in the table [here](https://github.com/Erkan-Yilmaz/GRC/issues/5) and below
* normally I don't get on forks so easily, but the last 3 days I also got on them :-(


<br>

![del_sb_forks](https://user-images.githubusercontent.com/642286/30847596-5fc3641e-a29c-11e7-996d-71b6d50c1cd2.png)

**Comment by tomasbrod** [comment]
Today's fork is 581/576 blocks deep. There were some oscillations, but now the main chain is noticeably heavier.

**Comment by Erkan-Yilmaz** [comment]
Poloniex has enabled deposit/withdrawal again (2017 Sep 26, 21:16 UTC+2)
